export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const SET_UNITS = 'SET_UNITS';
export const SET_LANGUAGE = 'SET_LANGUAGE';